@echo off
REM ============================================================================
REM RB BASIC (Ronen Blumberg BASIC) - Clean Temporary Files
REM Removes generated files and temporary compilation artifacts
REM ============================================================================

echo.
echo ============================================================================
echo RB BASIC - Clean Temporary Files
echo ============================================================================
echo.

REM Get the directory where this script is located
set RBBASIC_ROOT=%~dp0
set RBBASIC_ROOT=%RBBASIC_ROOT:~0,-1%

echo Cleaning temporary files in: %RBBASIC_ROOT%
echo.

REM Clean output directory
if exist "%RBBASIC_ROOT%\output\*.*" (
    echo Cleaning output\ directory...
    del /Q "%RBBASIC_ROOT%\output\*.*" 2>nul
    echo   [OK] Cleared output\ files
) else (
    echo   [OK] output\ directory is already clean
)

REM Remove generated C files in root
if exist "%RBBASIC_ROOT%\output.c" (
    del "%RBBASIC_ROOT%\output.c"
    echo   [OK] Removed output.c
)

if exist "%RBBASIC_ROOT%\program.c" (
    del "%RBBASIC_ROOT%\program.c"
    echo   [OK] Removed program.c
)

REM Remove shim file
if exist "%RBBASIC_ROOT%\shim_winmain.c" (
    del "%RBBASIC_ROOT%\shim_winmain.c"
    echo   [OK] Removed shim_winmain.c
)

REM Remove compile.bat (generated by compiler)
if exist "%RBBASIC_ROOT%\compile.bat" (
    del "%RBBASIC_ROOT%\compile.bat"
    echo   [OK] Removed compile.bat ^(will be regenerated^)
)

REM Remove compiled executables (optional - uncomment if needed)
REM if exist "%RBBASIC_ROOT%\program.exe" (
REM     del "%RBBASIC_ROOT%\program.exe"
REM     echo   [OK] Removed program.exe
REM )

REM Remove temporary object files
if exist "%RBBASIC_ROOT%\*.o" (
    del /Q "%RBBASIC_ROOT%\*.o"
    echo   [OK] Removed object files
)

REM Clean SDL2.dll if copied (optional - uncomment if you want to remove it)
REM if exist "%RBBASIC_ROOT%\SDL2.dll" (
REM     del "%RBBASIC_ROOT%\SDL2.dll"
REM     echo   [OK] Removed SDL2.dll
REM )

echo.
echo ============================================
echo Cleanup complete!
echo ============================================
echo.
echo Temporary files have been removed.
echo Your source files and rbbasic.exe are safe.
echo.

pause
