@echo off
REM ============================================================================
REM RB BASIC (Ronen Blumberg BASIC) - Setup & Validation
REM Validates installation and creates configuration
REM ============================================================================

echo.
echo ============================================================================
echo RB BASIC (Ronen Blumberg BASIC) - Portable Edition v2.0
echo Setup and Validation
echo ============================================================================
echo.

REM Get the directory where this script is located
set RBBASIC_ROOT=%~dp0
set RBBASIC_ROOT=%RBBASIC_ROOT:~0,-1%

echo Installation Directory: %RBBASIC_ROOT%
echo.

REM ============================================================================
echo Checking installation...
echo.

REM Check for rbbasic.exe
if not exist "%RBBASIC_ROOT%\rbbasic.exe" (
    echo [INFO] rbbasic.exe not found
    echo        You need to build the compiler first.
    echo        Run: build.bat
    echo.
) else (
    echo [OK] rbbasic.exe found
)

REM Check for MinGW32
if not exist "%RBBASIC_ROOT%\mingw32" (
    echo [ERROR] MinGW32 directory not found!
    echo Expected: %RBBASIC_ROOT%\mingw32
    echo.
    echo Please add MinGW32 compiler:
    echo   1. Download from https://winlibs.com
    echo   2. Get i686 ^(32-bit^) version
    echo   3. Extract to mingw32\ subfolder
    echo.
    set MINGW_MISSING=1
) else (
    if not exist "%RBBASIC_ROOT%\mingw32\bin\gcc.exe" (
        echo [ERROR] GCC compiler not found in MinGW32!
        echo Expected: %RBBASIC_ROOT%\mingw32\bin\gcc.exe
        echo.
        set MINGW_MISSING=1
    ) else (
        echo [OK] MinGW32 compiler found
        echo     %RBBASIC_ROOT%\mingw32\bin\gcc.exe
    )
)

REM Check for SDL2
if not exist "%RBBASIC_ROOT%\lib\SDL2-mingw32" (
    echo [INFO] SDL2 libraries not found ^(optional^)
    echo        Graphics features will not work without SDL2
    echo        Text-only programs will work fine
    echo.
    echo        To add SDL2:
    echo          1. Download from https://github.com/libsdl-org/SDL/releases
    echo          2. Get SDL2-devel-x.x.x-mingw.tar.gz
    echo          3. Extract i686-w64-mingw32 folder to lib\SDL2-mingw32\
    echo.
) else (
    echo [OK] SDL2 libraries found
    echo     Graphics support enabled
)

REM Check for source files
if not exist "%RBBASIC_ROOT%\src\main.cpp" (
    echo [WARNING] Source files not found in src\ folder
    echo           You won't be able to rebuild the compiler
    echo.
) else (
    echo [OK] Source files found in src\ folder
)

REM Check/create output directory
if not exist "%RBBASIC_ROOT%\output" (
    mkdir "%RBBASIC_ROOT%\output"
    echo [OK] Created output\ directory
) else (
    echo [OK] output\ directory exists
)

REM Check/create examples directory
if not exist "%RBBASIC_ROOT%\examples" (
    mkdir "%RBBASIC_ROOT%\examples"
    echo [OK] Created examples\ directory
) else (
    echo [OK] examples\ directory exists
)

echo.
REM ============================================================================
echo Creating/updating configuration...
echo.

REM Create or update rbc.config
(
    echo ; RB BASIC ^(Ronen Blumberg BASIC^) Configuration File
    echo ; Version 2.0 - Portable Edition
    echo ; Auto-generated by setup.bat
    echo.
    echo [Paths]
    echo CompilerRoot=.
    echo MinGW32Path=mingw32
    echo SDL2Path=lib\SDL2-mingw32
    echo OutputPath=output
    echo ExamplesPath=examples
    echo.
    echo [Compiler]
    echo GCC=mingw32\bin\gcc.exe
    echo GPP=mingw32\bin\g++.exe
    echo Optimization=-O1
    echo Warnings=-Wall -Wno-unused-label -Wno-unknown-pragmas
    echo.
    echo [SDL2]
    echo IncludePath=lib\SDL2-mingw32\i686-w64-mingw32\include
    echo LibPath=lib\SDL2-mingw32\i686-w64-mingw32\lib
    echo BinPath=lib\SDL2-mingw32\i686-w64-mingw32\bin
    echo.
    echo [Options]
    echo AutoCopySDL=true
    echo CleanupTemp=false
    echo ShowCompileProgress=true
    echo VerboseOutput=false
) > "%RBBASIC_ROOT%\rbc.config"

echo [OK] Created/updated rbc.config
echo.

REM ============================================================================
echo.
echo ============================================================================
echo Setup Summary
echo ============================================================================
echo.

if defined MINGW_MISSING (
    echo STATUS: NOT READY - MinGW32 missing
    echo.
    echo ACTION REQUIRED:
    echo   1. Add MinGW32 compiler to mingw32\ folder
    echo   2. Run setup.bat again
    echo   3. Run build.bat to compile rbbasic.exe
    echo.
) else (
    if not exist "%RBBASIC_ROOT%\rbbasic.exe" (
        echo STATUS: READY TO BUILD
        echo.
        echo Next step: Run build.bat to compile rbbasic.exe
        echo.
    ) else (
        echo STATUS: READY TO USE!
        echo.
        echo RB BASIC is ready for use.
        echo.
        echo Quick Start:
        echo   1. Create a .BAS program in this folder
        echo   2. Run: rbbasic yourprogram.bas
        echo   3. Run: compile.bat
        echo   4. Run: program.exe
        echo.
        echo For help: rbbasic --help
        echo Documentation: See docs\ folder
        echo Examples: See examples\ folder
        echo.
    )
)

echo Configuration file: rbc.config
echo Installation: %RBBASIC_ROOT%
echo.
echo ============================================================================
echo.

pause
