@echo off
REM Generated by RB BASIC Compiler (Ronen Blumberg BASIC)
REM Portable Edition - Uses local MinGW32 compiler
echo.
echo Compiling with local GCC...
echo.

REM Compiler: C:\rbbasic-portable\mingw32\bin\gcc.exe
REM SDL2 Include: C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\include
REM SDL2 Library: C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\lib
REM SDL2 Binary: C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\bin

if not exist "C:\rbbasic-portable\mingw32\bin\gcc.exe" (
    echo ERROR: GCC compiler not found!
    echo Expected location: C:\rbbasic-portable\mingw32\bin\gcc.exe
    echo.
    echo Please ensure MinGW32 is installed in the correct location.
    echo Check rbc.config for path settings.
    pause
    exit /b 1
)

REM Compile the generated C code
"C:\rbbasic-portable\mingw32\bin\gcc.exe" -m32 ^
    -I"C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\include" ^
    -L"C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\lib" ^
    -Wall -Wno-unused-label -Wno-unknown-pragmas ^
    -std=c99 ^
    -O1 ^
    -s ^
    output.c ^
    shim_winmain.c ^
    -lmingw32 ^
    -lSDL2main ^
    -lSDL2 ^
    -luser32 ^
    -lgdi32 ^
    -lwinmm ^
    -limm32 ^
    -lole32 ^
    -loleaut32 ^
    -lversion ^
    -luuid ^
    -lm ^
    -o program.exe

if errorlevel 1 (
    echo.
    echo ============================================
    echo Compilation FAILED!
    echo ============================================
    pause
    exit /b 1
)

echo.
echo ============================================
echo Success! Created program.exe
echo ============================================
echo.

REM Copy SDL2.dll to current directory
if exist "C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\bin\SDL2.dll" (
    copy /Y "C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\bin\SDL2.dll" . >nul 2>&1
    if not errorlevel 1 echo SDL2.dll copied successfully.
    echo.
) else (
    echo Warning: SDL2.dll not found at C:\rbbasic-portable\lib\SDL2-mingw32\i686-w64-mingw32\bin
    echo Graphics programs may not run without SDL2.dll
    echo.
)

REM Compilation complete
