// main.cpp - RB BASIC (Ronen Blumberg BASIC) Compiler driver
// Portable Edition - Full GW-BASIC/QBasic compatible compiler

#include "lexer.h"
#include "parser.h"
#include "codegen.h"
#include "config.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <string>
#include <stdexcept>
#include <cctype>

#ifdef _WIN32
#include <windows.h>
#include <direct.h>
#define mkdir _mkdir
#else
#include <sys/stat.h>
#include <sys/types.h>
#endif

static void print_usage(const char* program_name) {
    std::cout << "RB BASIC Compiler v2.0 - Portable Edition\n";
    std::cout << "==========================================\n";
    std::cout << "Ronen Blumberg BASIC - Full GW-BASIC/QBasic compatible compiler\n\n";
    std::cout << "Usage: " << program_name << " <source.bas> [-o output.exe] [-c] [-v]\n";
    std::cout << "Options:\n";
    std::cout << "  -o <file>   Specify output executable name (default: program.exe)\n";
    std::cout << "  -c          Generate C code only (don't compile)\n";
    std::cout << "  -v          Verbose output\n";
    std::cout << "  -h, --help  Show this help message\n";
    std::cout << "\nSupported Features:\n";
    std::cout << "  Phase 1: INPUT, LINE INPUT, String operations, Math functions, Arrays\n";
    std::cout << "  Phase 2: WHILE/WEND, DO/LOOP, GOSUB/RETURN, Block IF/THEN/ELSE\n";
    std::cout << "  Phase 3: DATA/READ/RESTORE, SUB/FUNCTION, File I/O\n";
    std::cout << "  Graphics: SCREEN, PSET, LINE, CIRCLE, PAINT (SDL2-based)\n";
    std::cout << "  Sound: SOUND, PLAY, BEEP\n\n";
    std::cout << "This is a portable installation. No system PATH configuration required.\n";
}

static std::string read_file(const std::string& filename) {
    std::ifstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot open file: " + filename);
    }
    std::ostringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

static bool ends_with_ci(const std::string& s, const std::string& suffix) {
    if (s.size() < suffix.size()) return false;
    for (size_t i = 0; i < suffix.size(); ++i) {
        unsigned char a = static_cast<unsigned char>(s[s.size() - suffix.size() + i]);
        unsigned char b = static_cast<unsigned char>(suffix[i]);
        if (std::tolower(a) != std::tolower(b)) return false;
    }
    return true;
}

static void write_winmain_shim(const std::string& path) {
    std::ofstream shim(path, std::ios::binary);
    if (!shim) throw std::runtime_error("Cannot write shim file: " + path);
    shim <<
R"(#ifdef _WIN32
#include <windows.h>
#include <stdio.h>
extern int main(int, char**);
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    AllocConsole();
    FILE *dummy;
    freopen_s(&dummy, "CONOUT$", "w", stdout);
    freopen_s(&dummy, "CONOUT$", "w", stderr);
    freopen_s(&dummy, "CONIN$", "r", stdin);
    return main(__argc, __argv);
}
#endif
)";
    shim.close();
}

static void create_directory(const std::string& path) {
    #ifdef _WIN32
    _mkdir(path.c_str());
    #else
    mkdir(path.c_str(), 0755);
    #endif
}

static void write_compile_bat(const std::string& path, RBConfig& config, 
                              const std::string& output_c, const std::string& output_exe,
                              const std::string& shim_file, bool uses_graphics, bool verbose) {
    std::ofstream bat(path);
    bat << "@echo off\n";
    bat << "REM Generated by RB BASIC Compiler (Ronen Blumberg BASIC)\n";
    bat << "REM Portable Edition - Uses local MinGW32 compiler\n";
    bat << "echo.\n";
    bat << "echo Compiling with local GCC...\n";
    bat << "echo.\n\n";
    
    // Get paths from config
    std::string gcc_path = config.get_gcc_path();
    std::string sdl2_inc = config.get_sdl2_include_path();
    std::string sdl2_lib = config.get_sdl2_lib_path();
    std::string sdl2_bin = config.get_sdl2_bin_path();
    std::string optimization = config.get("Compiler", "Optimization", "-O1");
    std::string warnings = config.get("Compiler", "Warnings", "-Wall -Wno-unused-label");
    
    bat << "REM Compiler: " << gcc_path << "\n";
    bat << "REM SDL2 Include: " << sdl2_inc << "\n";
    bat << "REM SDL2 Library: " << sdl2_lib << "\n";
    bat << "REM SDL2 Binary: " << sdl2_bin << "\n\n";
    
    // Check if GCC exists
    bat << "if not exist \"" << gcc_path << "\" (\n";
    bat << "    echo ERROR: GCC compiler not found!\n";
    bat << "    echo Expected location: " << gcc_path << "\n";
    bat << "    echo.\n";
    bat << "    echo Please ensure MinGW32 is installed in the correct location.\n";
    bat << "    echo Check rbc.config for path settings.\n";
    bat << "    pause\n";
    bat << "    exit /b 1\n";
    bat << ")\n\n";
    
    // Compile command
    bat << "REM Compile the generated C code\n";
    bat << "\"" << gcc_path << "\" -m32 ^\n";
    bat << "    -I\"" << sdl2_inc << "\" ^\n";
    bat << "    -L\"" << sdl2_lib << "\" ^\n";
    bat << "    " << warnings << " ^\n";
    bat << "    -std=c99 ^\n";
    bat << "    " << optimization << " ^\n";
    bat << "    -s ^\n";
    bat << "    " << output_c << " ^\n";
    
    // Only include shim for text-mode programs
    if (!uses_graphics) {
        bat << "    " << shim_file << " ^\n";
    }
    
    bat << "    -lmingw32 ^\n";
    bat << "    -lSDL2main ^\n";
    bat << "    -lSDL2 ^\n";
    bat << "    -luser32 ^\n";
    bat << "    -lgdi32 ^\n";
    bat << "    -lwinmm ^\n";
    bat << "    -limm32 ^\n";
    bat << "    -lole32 ^\n";
    bat << "    -loleaut32 ^\n";
    bat << "    -lversion ^\n";
    bat << "    -luuid ^\n";
    bat << "    -lm ^\n";
    bat << "    -o " << output_exe << "\n\n";
    
    bat << "if errorlevel 1 (\n";
    bat << "    echo.\n";
    bat << "    echo ============================================\n";
    bat << "    echo Compilation FAILED!\n";
    bat << "    echo ============================================\n";
    bat << "    pause\n";
    bat << "    exit /b 1\n";
    bat << ")\n\n";
    
    bat << "echo.\n";
    bat << "echo ============================================\n";
    bat << "echo Success! Created " << output_exe << "\n";
    bat << "echo ============================================\n";
    bat << "echo.\n\n";
    
    // Copy SDL2.dll if enabled
    if (config.get_bool("Options", "AutoCopySDL", true)) {
        bat << "REM Copy SDL2.dll to current directory\n";
        bat << "if exist \"" << sdl2_bin << "\\SDL2.dll\" (\n";
        bat << "    copy /Y \"" << sdl2_bin << "\\SDL2.dll\" . >nul 2>&1\n";
        bat << "    if not errorlevel 1 echo SDL2.dll copied successfully.\n";
        bat << "    echo.\n";
        bat << ") else (\n";
        bat << "    echo Warning: SDL2.dll not found at " << sdl2_bin << "\n";
        bat << "    echo Graphics programs may not run without SDL2.dll\n";
        bat << "    echo.\n";
        bat << ")\n\n";
    }
    
    bat << "REM Compilation complete\n";
    bat.close();
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    // Load configuration
    RBConfig config;
    if (!config.load("rbc.config")) {
        std::cout << "Note: Using default configuration settings.\n\n";
    }
    
    // Validate paths
    if (!config.validate_paths()) {
        std::cerr << "\nError: Configuration validation failed!\n";
        std::cerr << "Please check rbc.config and ensure all paths are correct.\n";
        return 1;
    }

    std::string source_file;
    std::string output_exe = "program.exe";
    std::string output_c   = "output.c";
    bool compile_only = false;
    bool verbose = config.get_bool("Options", "VerboseOutput", false);

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") {
            print_usage(argv[0]);
            return 0;
        } else if (arg == "-c") {
            compile_only = true;
        } else if (arg == "-v") {
            verbose = true;
        } else if (arg == "-o") {
            if (i + 1 < argc) {
                output_exe = argv[++i];
            } else {
                std::cerr << "Error: -o requires a filename\n";
                return 1;
            }
        } else if (!arg.empty() && arg[0] != '-') {
            source_file = arg;
        } else {
            std::cerr << "Error: Unknown option: " << arg << "\n";
            print_usage(argv[0]);
            return 1;
        }
    }

    if (source_file.empty()) {
        std::cerr << "Error: No source file specified\n";
        print_usage(argv[0]);
        return 1;
    }

    if (!ends_with_ci(output_exe, ".exe")) {
        output_exe += ".exe";
    }

    try {
        std::cout << "RB BASIC Compiler v2.0 - Portable Edition\n";
        std::cout << "==========================================\n";
        std::cout << "Ronen Blumberg BASIC\n\n";

        if (verbose) {
            std::cout << "Configuration:\n";
            std::cout << "  Compiler Root: " << config.get_compiler_root() << "\n";
            std::cout << "  GCC Path: " << config.get_gcc_path() << "\n";
            std::cout << "  SDL2 Include: " << config.get_sdl2_include_path() << "\n";
            std::cout << "\n";
        }

        std::cout << "Reading source file: " << source_file << "\n";
        std::string source = read_file(source_file);

        std::cout << "Lexical analysis...\n";
        Lexer lexer(source);
        auto tokens = lexer.tokenize();
        if (verbose) {
            std::cout << "  Tokens generated: " << tokens.size() << "\n";
        }

        std::cout << "Parsing...\n";
        Parser parser(tokens);
        auto program = parser.parse();
        if (verbose) {
            std::cout << "  Statements parsed: " << program->statements.size() << "\n";
            std::cout << "  SUBs defined: " << program->subs.size() << "\n";
            std::cout << "  FUNCTIONs defined: " << program->functions.size() << "\n";
        }

        std::cout << "Generating C code...\n";
        CodeGenerator codegen(output_c);
        codegen.generate(program.get());
        std::cout << "Code generation complete.\n";
        std::cout << "  Generated: " << output_c << "\n";

        // Only use WinMain shim for text-mode programs
        const std::string shim_file = "shim_winmain.c";
        bool uses_graphics = codegen.uses_graphics();
        
        if (!uses_graphics) {
            write_winmain_shim(shim_file);
            std::cout << "  Generated: " << shim_file << "\n";
        } else {
            if (verbose) {
                std::cout << "  Skipping shim (graphics mode detected)\n";
            }
        }

        if (compile_only) {
            std::cout << "\nC code generation complete.\n";
            return 0;
        }

        // Create compile.bat with config paths
        write_compile_bat("compile.bat", config, output_c, output_exe, shim_file, uses_graphics, verbose);

        std::cout << "\n========================================\n";
        std::cout << "Code generation complete!\n";
        std::cout << "To compile and run: compile.bat\n";
        std::cout << "========================================\n";
        
        return 0;

    } catch (const std::exception& e) {
        std::cerr << "\nError: " << e.what() << "\n";
        return 1;
    }
}
